/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicarmar.proyecto.vista;

import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hibernate.exception.ConstraintViolationException;
import practiarmar.proyecto.controlador.AgregarEmpleadoViewController;
import practiarmar.proyecto.modelo.Rol;

/**
 *
 * @author crist
 */
public class AgregarEmpleadoView extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEmpleadoView
     */
    private MenuPrincipal menu;
    private String rol;
    private AgregarEmpleadoViewController controller;

    public AgregarEmpleadoView(MenuPrincipal menu) {
        this.menu = menu;
        controller = new AgregarEmpleadoViewController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtUsername = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        labelRoles = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        comboRol = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1150, 704));
        setMinimumSize(new java.awt.Dimension(1150, 704));
        setPreferredSize(new java.awt.Dimension(1150, 704));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Datos del empleado");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 23, 621, 42));

        jLabel2.setText("Nombre");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 253, 26));

        jLabel3.setText("Telefono");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 249, 26));

        jLabel4.setText("Codigo");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 242, 26));

        jLabel5.setText("Usuario");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 140, 250, 26));

        jLabel6.setText("Contraseña");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 240, 263, 26));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1106, 20));

        txtNombre.setBorder(null);
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 423, 26));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 423, 20));

        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 423, 26));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 423, 20));

        txtCodigo.setBorder(null);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        bg.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 423, 26));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 420, 10));

        txtUsername.setBorder(null);
        bg.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 180, 423, 26));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 210, 423, 20));

        txtPassword.setBorder(null);
        bg.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 280, 423, 26));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 310, 423, 20));

        labelRoles.setText("Rol");
        bg.add(labelRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 33, 26));

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\guardar.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        bg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 259, 58));

        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\limpiar.png")); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 570, 257, 58));

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\volverI.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        bg.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 570, 250, 58));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 1106, 20));

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol", "Empleado", "Administrador" }));
        comboRol.setBorder(null);
        bg.add(comboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 420, 30));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 410, 420, 10));

        jLabel7.setText("Email");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 350, 232, 26));

        txtEmail.setBorder(null);
        bg.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 380, 423, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menu.showEmpleadoView();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) && c != '+') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtCodigo.setText("");
        txtPassword.setText("");
        txtTelefono.setText("");
        txtUsername.setText("");
        txtEmail.setText("");
        comboRol.setSelectedIndex(0);
        rol = "";
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validacionCampos()) {
            if (isEmailValid()) {
                System.out.println("guardado con exito desde la ventana");
                String nombre = txtNombre.getText();
                String codigo = txtCodigo.getText();
                String password = String.valueOf(txtPassword.getPassword());
                String telefono = txtTelefono.getText();
                String email = txtEmail.getText();
                String username = txtUsername.getText();

                switch (rol) {
                    case "Empleado":
                    {
                        try {
                            controller.crear(nombre, codigo, password, telefono, email, username, Rol.EMPLEADO);
                            JOptionPane.showMessageDialog(this,"Empleado agregado con exito!");
                            btnLimpiarActionPerformed(evt);
                        } catch (Exception ex) {
                            Logger.getLogger(AgregarEmpleadoView.class.getName()).log(Level.SEVERE, null, ex);
                            System.out.println("entro al catch de error de codigo empleado");
                             JOptionPane.showMessageDialog(this,"No es posible que dos empleados tengan el mismo codigo, por favor cambielo\n");
                        }
                    }
                               break;

                           
                    case "Administrador":
                    {
                        try {
                            controller.crear(nombre, codigo, password, telefono, email, username, Rol.ADMINISTRADOR);
                            JOptionPane.showMessageDialog(this,"Empleado agregado con exito!");
                            btnLimpiarActionPerformed(evt);
                        } catch (Exception ex) {
                            Logger.getLogger(AgregarEmpleadoView.class.getName()).log(Level.SEVERE, null, ex);
                            System.out.println("entro al catch de error de codigo empleado");
                            JOptionPane.showMessageDialog(this,"No es posible que dos empleados tengan el mismo codigo, por favor cambielo\n");
                        }
                    }
                        break;


                    default:
                        JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar los datos!");
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar un email valido!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos!");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    private boolean isEmailValid() {
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        return txtEmail.getText().matches(EMAIL_PATTERN);
    }

    private boolean validacionCampos() {
        if (txtNombre.getText().equals("") || txtCodigo.getText().equals("")
                || String.valueOf(txtPassword.getPassword()).isEmpty() || txtTelefono.getText().equals("")
                || txtUsername.getText().equals("") || !isRolSeleccionado() || txtEmail.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private boolean isRolSeleccionado() {
        rol = (String) comboRol.getSelectedItem();
        if (rol.equalsIgnoreCase("Seleccione un rol")) {
            rol = "";
            return false;
        } else {
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel labelRoles;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
