/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicarmar.proyecto.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import practiarmar.proyecto.controlador.ClienteAgregarEditarViewController;
import practiarmar.proyecto.modelo.Cliente;

/**
 *
 * @author crist
 */
public class ClienteAgregarEditarView extends javax.swing.JPanel {

    /**
     * Creates new form ClientePanelView
     */
    private Cliente c;
    private MenuPrincipal menu;
    private boolean esNuevo = false;
    private ClienteAgregarEditarViewController controller;

    public ClienteAgregarEditarView(MenuPrincipal menu, Cliente c) {
        this.c = c;
        this.menu = menu;
        this.controller = new ClienteAgregarEditarViewController();
        initComponents();
        mostrarDatos();
    }

    private void mostrarDatos() {
        if (c != null) {
            txtId.setText(String.valueOf(c.getId()));
            txtNombre.setText(c.getNombre());
            txtTelefono.setText(c.getTelefono());
            txtEmail.setText(c.getEmail());
            if (c.isRecibirNotificaciones()) {
                comboNotificaciones.setSelectedIndex(1);
            } else {
                comboNotificaciones.setSelectedIndex(2);
            }
        } else {
            esNuevo = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboNotificaciones = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1150, 704));
        setMinimumSize(new java.awt.Dimension(1150, 704));
        setPreferredSize(new java.awt.Dimension(1150, 704));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Datos del cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 585, 34));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 82, 1106, 39));

        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 18));

        txtId.setBorder(null);
        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, 18));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 220, 18));

        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 310, 18));

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 210, 18));

        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 310, 18));

        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 210, 18));

        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 310, -1));

        jLabel6.setText("Recibir notificaciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 270, 18));

        comboNotificaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Si", "No" }));
        jPanel1.add(comboNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 310, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 1106, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 310, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 310, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 310, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 310, 10));

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\guardar.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 575, 255, 79));

        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\limpiar.png")); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(106, 37));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 575, 255, 79));

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\volverI.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setPreferredSize(new java.awt.Dimension(106, 37));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 575, 256, 79));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        comboNotificaciones.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (camposValidos()) {
            if (isEmailValid()) {
                if (esNuevo) {
                    String nombre = txtNombre.getText();
                    String telefono = txtTelefono.getText();
                    String email = txtEmail.getText();
                    Cliente nuevoCliente = new Cliente();
                    if (comboNotificaciones.getSelectedIndex() == 1) {
                        //si
                        nuevoCliente.setNombre(nombre);
                        nuevoCliente.setTelefono(telefono);
                        nuevoCliente.setEmail(email);
                        nuevoCliente.setRecibirNotificaciones(true);
                        controller.agregar(nuevoCliente);

                    } else {
                        //no
                        nuevoCliente.setNombre(nombre);
                        nuevoCliente.setTelefono(telefono);
                        nuevoCliente.setEmail(email);
                        nuevoCliente.setRecibirNotificaciones(false);
                        controller.agregar(nuevoCliente);
                    }
                    JOptionPane.showMessageDialog(null, "Se agrego el cliente con exito!");
                    btnVolverActionPerformed(evt);
                } else {
                    c.setNombre(txtNombre.getText());
                    c.setTelefono(txtTelefono.getText());
                    c.setEmail(txtEmail.getText());
                    if (comboNotificaciones.getSelectedIndex() == 1) {
                        //si
                        c.setRecibirNotificaciones(true);
                        try {
                            controller.editar(c);
                            JOptionPane.showMessageDialog(null, "Se edito el cliente con exito!");
                            btnVolverActionPerformed(evt);
                        } catch (Exception ex) {
                            Logger.getLogger(ClienteAgregarEditarView.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null, "Ocurrio un error al editar el cliente!\n" + ex.getLocalizedMessage());
                        }
                    } else {
                        //no
                        c.setRecibirNotificaciones(false);
                        try {
                            controller.editar(c);
                            JOptionPane.showMessageDialog(null, "Se edito el cliente con exito!");
                            btnVolverActionPerformed(evt);
                        } catch (Exception ex) {
                            Logger.getLogger(ClienteAgregarEditarView.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null, "Ocurrio un error al editar el cliente!\n" + ex.getLocalizedMessage());
                        }
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un email valido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menu.showClienteView();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) && c != '+') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped
    private boolean isEmailValid() {
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        return txtEmail.getText().matches(EMAIL_PATTERN);
    }

    private boolean camposValidos() {
        return !(txtNombre.getText().equals("") || txtTelefono.getText().equals("")
                || txtEmail.getText().equals("") || comboNotificaciones.getSelectedIndex() == 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboNotificaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
