/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicarmar.proyecto.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import practiarmar.proyecto.controlador.EditarEmpleadoViewController;
import practiarmar.proyecto.modelo.Rol;
import practiarmar.proyecto.modelo.Empleado;

/**
 *
 * @author crist
 */
public class EditarEmpleadoView extends javax.swing.JPanel {

    /**
     * Creates new form EditarEmpleadoView
     */
    private String rol;
    private MenuPrincipal menu;
    private Empleado empleadoAEditar;
    private EditarEmpleadoViewController controller = new EditarEmpleadoViewController();

    public EditarEmpleadoView(Empleado empleadoAEditar, MenuPrincipal menu) {
        this.menu = menu;
        this.empleadoAEditar = empleadoAEditar;
        initComponents();
        mostrarDatosEmpleado();
    }

    private void mostrarDatosEmpleado() {
        txtId.setText(String.valueOf(empleadoAEditar.getId()));
        txtNombre.setText(empleadoAEditar.getNombre());
        txtTelefono.setText(empleadoAEditar.getTelefono());
        txtCodigo.setText(empleadoAEditar.getCodigo());
        txtUsername.setText(empleadoAEditar.getUsername());
        txtEmail.setText(empleadoAEditar.getEmail());
        if (empleadoAEditar.getRol().equals(Rol.EMPLEADO)) {
            comboRol.setSelectedIndex(1);
        } else {
            comboRol.setSelectedItem(2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(1150, 704));
        setMinimumSize(new java.awt.Dimension(1150, 704));
        setPreferredSize(new java.awt.Dimension(744, 550));

        jPanel1.setMaximumSize(new java.awt.Dimension(1150, 704));
        jPanel1.setMinimumSize(new java.awt.Dimension(1150, 704));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelInfo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelInfo.setText("Datos del empleado a editar");
        jPanel1.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 707, 42));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1105, 20));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 247, 26));

        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 382, 26));

        jLabel2.setText("Telefono");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 248, 26));

        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 382, 26));

        jLabel3.setText("Codigo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 393, 23));

        txtCodigo.setBorder(null);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 459, 380, 23));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 130, 247, 26));

        txtUsername.setBorder(null);
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 160, 383, 26));

        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 230, 262, 26));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 330, 232, 26));

        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 360, 383, 26));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 382, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 382, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 380, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 190, 383, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 290, 383, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 390, 383, 20));

        jLabel7.setText("Rol");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 68, 23));

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol", "Empleado", "Administrador" }));
        comboRol.setBorder(null);
        jPanel1.add(comboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 390, 27));

        jLabel8.setText("Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 218, 26));

        txtId.setBorder(null);
        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 382, 26));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 382, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 526, 1105, 20));

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\guardar.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 576, 243, 60));

        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\limpiar.png")); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(106, 37));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 576, 245, 60));

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\cancelar.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(106, 37));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 576, 247, 60));

        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 260, 383, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean isEmailValid() {
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        return txtEmail.getText().matches(EMAIL_PATTERN);
    }

    private boolean validacionCampos() {
        if (txtNombre.getText().equals("") || txtCodigo.getText().equals("")
                || String.valueOf(txtPassword.getPassword()).isEmpty() || txtTelefono.getText().equals("")
                || txtUsername.getText().equals("") || !isRolSeleccionado() || txtEmail.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private boolean isRolSeleccionado() {
        rol = (String) comboRol.getSelectedItem();
        if (rol.equalsIgnoreCase("Seleccione un rol")) {
            rol = "";
            return false;
        } else {
            return true;
        }
    }

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) && c != '+') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtCodigo.setText("");
        txtPassword.setText("");
        txtTelefono.setText("");
        txtUsername.setText("");
        txtEmail.setText("");
        comboRol.setSelectedIndex(0);
        rol = "";
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validacionCampos()) {
            if (isEmailValid()) {
                String nombre = txtNombre.getText();
                String codigo = txtCodigo.getText();
                String password = String.valueOf(txtPassword.getPassword());
                String telefono = txtTelefono.getText();
                String email = txtEmail.getText();
                String username = txtUsername.getText();
                switch (rol) {
                    case "Empleado":
                        empleadoAEditar.setNombre(nombre);
                        empleadoAEditar.setCodigo(codigo);
                        empleadoAEditar.setContrasena(password);
                        empleadoAEditar.setTelefono(telefono);
                        empleadoAEditar.setEmail(email);
                        empleadoAEditar.setUsername(username);
                        empleadoAEditar.setRol(Rol.EMPLEADO);
                         {
                            try {
                                controller.editar(empleadoAEditar);
                                JOptionPane.showMessageDialog(this, "Modificacion con exito!");
                                btnLimpiarActionPerformed(evt);
                                btnCancelarActionPerformed(evt);
                            } catch (Exception ex) {
                                Logger.getLogger(EditarEmpleadoView.class.getName()).log(Level.SEVERE, null, ex);
                                JOptionPane.showMessageDialog(this, "Ocurrio un error al editar el empleado!\n" + ex.getLocalizedMessage());
                            }
                        }
                        break;

                    case "Administrador":
                        empleadoAEditar.setNombre(nombre);
                        empleadoAEditar.setCodigo(codigo);
                        empleadoAEditar.setContrasena(password);
                        empleadoAEditar.setTelefono(telefono);
                        empleadoAEditar.setEmail(email);
                        empleadoAEditar.setUsername(username);
                        empleadoAEditar.setRol(Rol.ADMINISTRADOR);
                         {
                            try {
                                controller.editar(empleadoAEditar);
                                JOptionPane.showMessageDialog(this, "Modificacion con exito!");
                                btnLimpiarActionPerformed(evt);
                                btnCancelarActionPerformed(evt);
                            } catch (Exception ex) {
                                Logger.getLogger(EditarEmpleadoView.class.getName()).log(Level.SEVERE, null, ex);
                                JOptionPane.showMessageDialog(this, "Ocurrio un error al editar el empleado!\n" + ex.getLocalizedMessage());
                            }
                        }
                        break;

                    default:
                        JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar los datos!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar un email valido!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos!");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        menu.showEmpleadoView();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
