/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicarmar.proyecto.vista;

import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import practiarmar.proyecto.controlador.ProyectoPanelViewController;
import practiarmar.proyecto.modelo.EstadoProyecto;
import practiarmar.proyecto.modelo.Proyecto;
import practiarmar.proyecto.persistence.exceptions.NonexistentEntityException;

/**
 *
 * @author crist
 */
public class ProyectoPanelView extends javax.swing.JPanel {

    /**
     * Creates new form ProyectoPanelView
     */
    private MenuPrincipal menu;
    private ProyectoPanelViewController controller;
    private Proyecto proyecto = null;
    private DefaultTableModel modelo;
    private List<Proyecto> proyectos;
    

    public ProyectoPanelView(MenuPrincipal menu) {
        this.menu = menu;
        this.controller = new ProyectoPanelViewController();
        initComponents();
        modelo = (DefaultTableModel) tblProyectos.getModel();
        llenarTablaProyectos();
    }

    private void llenarTablaProyectos() {
        modelo.setRowCount(0);
        obtenerProyectos();
       if(proyectos!=null && !proyectos.isEmpty()){
            Object rowData[] = new Object[5];
        for (Proyecto p : proyectos) {
            rowData[0] = p.getId();
            rowData[1] = p.getFechaEntrega();
            rowData[2] = saberEstado(p.getEstadoProyecto());
            modelo.addRow(rowData);
        }
       }
    }

    private String saberEstado(EstadoProyecto estado) {
        return switch (estado) {
            case CANCELADO -> "CANCELADO";
            case ESPERA_DE_PAGO -> "ESPERA DE PAGO";
            case FINALIZADO -> "FINALIZADO";
            case EN_CURSO -> "EN CURSO";
            case SIN_EMPEZAR -> "SIN EMPEZAR";
            default -> "";
        };

    }

    private void obtenerProyectos() {
        this.proyectos = controller.obtenerProyectos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProyectos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnHacerCotzacion = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1150, 704));
        setMinimumSize(new java.awt.Dimension(1150, 704));
        setPreferredSize(new java.awt.Dimension(1150, 704));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Proyectos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 860, 10));

        jLabel2.setText("Filtro");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 30, 20));

        txtFiltro.setBorder(null);
        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });
        jPanel1.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 820, -1));

        tblProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Entrega", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProyectos.setShowHorizontalLines(true);
        tblProyectos.setShowVerticalLines(true);
        tblProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProyectosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProyectos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 163, 860, 520));

        btnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\agregar.png")); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 164, 56));

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\editar.png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 163, 56));

        btnVer.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\ver.png")); // NOI18N
        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 163, 56));

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\eliminar.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 163, 56));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 820, 20));

        btnHacerCotzacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\presupuestoImagen.png")); // NOI18N
        btnHacerCotzacion.setText("Cotizar");
        btnHacerCotzacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerCotzacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnHacerCotzacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 163, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProyectosMouseClicked
         Long id = (Long) modelo.getDataVector().elementAt(tblProyectos.convertRowIndexToModel(tblProyectos.getSelectedRow())).get(0);
        for (Proyecto p : proyectos) {
            if (Objects.equals(p.getId(), id)) {
                proyecto = p;
                break;
            }
        }
    }//GEN-LAST:event_tblProyectosMouseClicked

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
           char c = evt.getKeyChar();
    if (!Character.isLetterOrDigit(c)) {
        evt.consume();
    }
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        String filtro = txtFiltro.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(modelo);
        tblProyectos.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(filtro));
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
           menu.showProyectoAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       if(proyecto!=null){
           menu.showProyectoEditar(proyecto);
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proyecto!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
       if(proyecto!=null){
            menu.showVerProyecto(proyecto);
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proyecto!");
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(proyecto!=null){
            try {
                proyecto.setDeleted(true);
                controller.removeProyecto(proyecto);
                JOptionPane.showMessageDialog(this, "Proyecto eliminado con exito!");
                proyecto=null;
                llenarTablaProyectos();
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(ProyectoPanelView.class.getName()).log(Level.SEVERE, null, ex);
                
            JOptionPane.showMessageDialog(this, "Ocurrio un error al intentar eliminar el proyecto!\n"+ex.getLocalizedMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proyecto!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void btnHacerCotzacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerCotzacionActionPerformed
        menu.showCotizarView();
    }//GEN-LAST:event_btnHacerCotzacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHacerCotzacion;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblProyectos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
