/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practicarmar.proyecto.vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import practiarmar.proyecto.modelo.Empleado;
import practiarmar.proyecto.modelo.Foto;
import practiarmar.proyecto.modelo.Item;
import practiarmar.proyecto.modelo.Cliente;
import practiarmar.proyecto.modelo.Proyecto;

/**
 *
 * @author crist
 */
public class VerProyectoView extends javax.swing.JPanel {

    private List<Empleado> empleados;
    private List<Item> items;
    private List<Foto> fotos;
    private Cliente cliente;
    private MenuPrincipal menu;
    private DefaultTableModel modelEmpleados;
    private DefaultTableModel modelItems;
    private DefaultTableModel modelFotos;
    private Proyecto p;
    private DecimalFormat decimalFormat;

    /**
     * Creates new form VerProyectoView
     */
    public VerProyectoView(Proyecto proyecto, MenuPrincipal menu) {
        this.menu = menu;
        p = proyecto;
        empleados = proyecto.getEmpleados();
        items = proyecto.getItems();
        fotos = proyecto.getFotos();
        cliente = proyecto.getCliente();
        decimalFormat = new DecimalFormat("#,##0");
        initComponents();

        modelEmpleados = (DefaultTableModel) tblEmpleados.getModel();
        modelItems = (DefaultTableModel) tblItems.getModel();
        modelFotos = (DefaultTableModel) tblFotos.getModel();

        rellenarTablaEmpleados();
        rellenarTablaFotos();
        rellenarTablaItems();
        rellenarCampos();
    }

    private void rellenarCampos() {
        txtId.setText(String.valueOf(p.getId()));
        jformatPrecioManoObra.setText(decimalFormat.format(p.getPrecioManoDeObra()));
        jformatPrecioPorEmpleado.setText(decimalFormat.format(p.getPrecioPorEmpleado()));
        jformatPrecioMateriales.setText(decimalFormat.format(p.getPrecioMateriales()));
        txtCliente.setText(cliente.getNombre());
        txtEstado.setText(p.getEstadoProyecto().toString());
        txtAreaDescripcion.setText(p.getDescripcion());
        txtFechaEntrega.setText(String.valueOf(p.getFechaEntrega()));
        txtUltimaModificacion.setText(String.valueOf(p.getFehcaModificacion()));
        jformarPrecioTotal.setText(decimalFormat.format(p.getPrecioTotal()));

    }

    private void rellenarTablaEmpleados() {
        if (empleados != null && !empleados.isEmpty()) {
            Object rowData[] = new Object[1];
            for (Empleado empleado : empleados) {
                rowData[0] = empleado.getNombre();
                //TODO: agregar el codigo del empleado
                modelEmpleados.addRow(rowData);
            }
        }
    }

    private void rellenarTablaFotos() {
        if (fotos != null && !fotos.isEmpty()) {
            Object rowData[] = new Object[1];
            for (Foto foto : fotos) {
                rowData[0] = foto.getNombre();
                modelFotos.addRow(rowData);
            }
        }
    }

    private void rellenarTablaItems() {
        if (items != null && !items.isEmpty()) {
            Object rowData[] = new Object[2];
            for (Item item : items) {
                rowData[0] = item.getNombre();
                rowData[1] = item.getCantidad();
                modelItems.addRow(rowData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtFechaEntrega = new javax.swing.JTextField();
        txtUltimaModificacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFotos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jformatPrecioMateriales = new javax.swing.JFormattedTextField();
        jformatPrecioPorEmpleado = new javax.swing.JFormattedTextField();
        jformatPrecioManoObra = new javax.swing.JFormattedTextField();
        jformarPrecioTotal = new javax.swing.JFormattedTextField();

        setMaximumSize(new java.awt.Dimension(1150, 704));
        setMinimumSize(new java.awt.Dimension(1150, 704));

        jPanel1.setMaximumSize(new java.awt.Dimension(1150, 704));
        jPanel1.setMinimumSize(new java.awt.Dimension(1150, 704));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 704));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Datos del proyecto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1090, 10));

        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setText("precio mano de obra");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setText("precio pago por empleado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setText("precio materiales");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setText("cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel8.setText("fecha de entrega");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel9.setText("ultima modificacion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel10.setText("precio total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel11.setText("descripcion");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        txtId.setEditable(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 240, -1));

        txtCliente.setEditable(false);
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 240, -1));

        txtEstado.setEditable(false);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 240, -1));

        txtFechaEntrega.setEditable(false);
        jPanel1.add(txtFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 240, -1));

        txtUltimaModificacion.setEditable(false);
        jPanel1.add(txtUltimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 240, -1));

        txtAreaDescripcion.setEditable(false);
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setRows(5);
        txtAreaDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 240, 120));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEmpleados);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 240, 190));

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblItems);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 200, 500));

        tblFotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblFotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFotosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblFotos);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 240, 200));

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Documentos\\NetBeansProjects\\practiarmar\\src\\main\\resources\\volverI.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 140, 50));

        jLabel12.setText("Fotos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        jLabel13.setText("Empleados");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel14.setText("Items");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 1090, 10));

        jformatPrecioMateriales.setEditable(false);
        jPanel1.add(jformatPrecioMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, -1));

        jformatPrecioPorEmpleado.setEditable(false);
        jPanel1.add(jformatPrecioPorEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, -1));

        jformatPrecioManoObra.setEditable(false);
        jPanel1.add(jformatPrecioManoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, -1));

        jformarPrecioTotal.setEditable(false);
        jPanel1.add(jformarPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menu.showProyectoPanel();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblFotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFotosMouseClicked
        //TODO: mostrar la foto en una ventana nueva, y que hasta no cerrar la venta, no dejar hacer ninguna accion
        String nombreFoto = (String) modelFotos.getDataVector().elementAt(tblFotos.convertRowIndexToModel(tblFotos.getSelectedRow())).get(0);
        for (Foto foto : fotos) {
            if (foto.getNombre().equals(nombreFoto)) {
                
                VerFotoView fotoView = new VerFotoView(menu, true);
                fotoView.setLocationRelativeTo(null);
                fotoView.setFoto(foto);
                fotoView.showFoto();
                fotoView.setVisible(true);
                break;
            }
        }


    }//GEN-LAST:event_tblFotosMouseClicked

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
        String nombreItem = (String) modelItems.getDataVector().elementAt(tblItems.convertRowIndexToModel(tblItems.getSelectedRow())).get(0);
        for (Item item : items) {
            if(item.getNombre().equals(nombreItem)){
               VerItemView itemView = new VerItemView(menu, true);
               itemView.setLocationRelativeTo(null);
               itemView.setITem(item);
               itemView.mostrarDatos();
               itemView.setVisible(true);
               break;
            }
        }
    }//GEN-LAST:event_tblItemsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField jformarPrecioTotal;
    private javax.swing.JFormattedTextField jformatPrecioManoObra;
    private javax.swing.JFormattedTextField jformatPrecioMateriales;
    private javax.swing.JFormattedTextField jformatPrecioPorEmpleado;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTable tblFotos;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtUltimaModificacion;
    // End of variables declaration//GEN-END:variables
}
